// Daily Czech — vocabulary export
// Upload this file as vocab.js to your GitHub Pages repo root.
// The app fetches it on every load and merges new words automatically.
// To add more words: append entries to the array and push.
//
// Current count: 1628 words
// Sources: Duolingo export + Ling Anki deck
//
const VOCAB_EXT = [
  {cz:"... půl",en:"half"},
  {cz:"1. ledna",en:"January first"},
  {cz:"14. února",en:"February fourteenth"},
  {cz:"25. prosince",en:"December twenty-fifth"},
  {cz:"a",en:"and"},
  {cz:"abeceda",en:"alphabet"},
  {cz:"ahoj",en:"hello"},
  {cz:"ale",en:"but"},
  {cz:"alkohol",en:"alcohol"},
  {cz:"ambasáda",en:"embassy"},
  {cz:"analyzovat",en:"to analyze"},
  {cz:"anděl",en:"angel"},
  {cz:"anebo",en:"or"},
  {cz:"anglicky",en:"English"},
  {cz:"angličtina",en:"English"},
  {cz:"ani",en:"even"},
  {cz:"ano",en:"yes"},
  {cz:"asi",en:"probably"},
  {cz:"astronaut",en:"astronaut"},
  {cz:"atmosféra",en:"atmosphere"},
  {cz:"auta",en:"car"},
  {cz:"auto",en:"car"},
  {cz:"autobus",en:"a bus"},
  {cz:"autobusová zastávka",en:"bus stop"},
  {cz:"autobusové nádraží",en:"a bus station"},
  {cz:"babička",en:"grandmother"},
  {cz:"balík",en:"package"},
  {cz:"banka",en:"bank"},
  {cz:"bankovka",en:"bank note"},
  {cz:"bankovní účet",en:"bank account"},
  {cz:"banán",en:"banana"},
  {cz:"barva",en:"light's"},
  {cz:"basketball",en:"basketball"},
  {cz:"bazén",en:"swimming pool; a swimming pool"},
  {cz:"bez",en:"without"},
  {cz:"beze",en:"without"},
  {cz:"blesk",en:"lightning"},
  {cz:"blog",en:"blog"},
  {cz:"blond",en:"blonde"},
  {cz:"blízko",en:"near"},
  {cz:"bohatý",en:"rich"},
  {cz:"bolení břicha",en:"stomachache"},
  {cz:"bolest",en:"pain"},
  {cz:"bolest hlavy",en:"headache"},
  {cz:"bolest ramene",en:"shoulder pain"},
  {cz:"bolest zubů",en:"toothache"},
  {cz:"bolet",en:"hurt"},
  {cz:"bonus",en:"bonus"},
  {cz:"bota",en:"shoe"},
  {cz:"boty",en:"shoes"},
  {cz:"bouřka",en:"storm"},
  {cz:"brambora",en:"a potato"},
  {cz:"bratr",en:"brother"},
  {cz:"bratranec",en:"cousin"},
  {cz:"broskev",en:"a peach"},
  {cz:"brož",en:"brooch"},
  {cz:"brát",en:"takes"},
  {cz:"budoucnost",en:"future"},
  {cz:"bunda",en:"jacket"},
  {cz:"buď",en:"be"},
  {cz:"Buď opatrný!",en:"Be careful!"},
  {cz:"bydlet",en:"to live"},
  {cz:"byl",en:"ve"},
  {cz:"byla",en:"they were"},
  {cz:"bylas",en:"you were"},
  {cz:"byli",en:"were"},
  {cz:"bylo",en:"it was"},
  {cz:"byls",en:"you were"},
  {cz:"byly",en:"were"},
  {cz:"byt",en:"apartment"},
  {cz:"bát",en:"to be afraid"},
  {cz:"bát se",en:"to be scared"},
  {cz:"bílá",en:"white"},
  {cz:"bílé víno",en:"white wine"},
  {cz:"bílý",en:"white"},
  {cz:"být",en:"to be"},
  {cz:"být alergický",en:"to be allergic"},
  {cz:"být hladový",en:"to be hungry"},
  {cz:"být k dispozici",en:"to be available"},
  {cz:"být líto",en:"to be sorry"},
  {cz:"být milý",en:"to be kind"},
  {cz:"být mlhavo",en:"to be foggy"},
  {cz:"být na dietě",en:"to be on a diet"},
  {cz:"být překrásný",en:"to be beautiful"},
  {cz:"být připraven",en:"to be ready"},
  {cz:"být přátelský",en:"to be friendly"},
  {cz:"být přísný",en:"to be strict"},
  {cz:"být rozveden",en:"to be divorced"},
  {cz:"být rád",en:"to be glad"},
  {cz:"být si jistý",en:"to be sure"},
  {cz:"být slavný",en:"to be famous"},
  {cz:"být smutný",en:"to be sad"},
  {cz:"být svobodný",en:"to be single"},
  {cz:"být upřímný",en:"to be sincere; to be honest"},
  {cz:"být v klidu",en:"to be calm"},
  {cz:"být v manželství",en:"to be married"},
  {cz:"být vegetarián",en:"to be vegetarian"},
  {cz:"být vážný",en:"to be serious"},
  {cz:"být zabouchnutý",en:"to have a crush on"},
  {cz:"být zasnoubený",en:"to be engaged"},
  {cz:"být zataženo",en:"to be cloudy"},
  {cz:"být zkažený",en:"to be spoiled"},
  {cz:"být šťastný",en:"to be happy"},
  {cz:"bývalý",en:"former"},
  {cz:"běhat",en:"to run"},
  {cz:"běžet",en:"to run"},
  {cz:"březen",en:"March"},
  {cz:"celý",en:"whole"},
  {cz:"centimetr",en:"centimeter"},
  {cz:"cesta",en:"trip"},
  {cz:"cestovat",en:"to travel"},
  {cz:"cestovní pas",en:"Passport"},
  {cz:"cestující",en:"a passenger"},
  {cz:"chatovat",en:"to chat"},
  {cz:"chilli",en:"chili"},
  {cz:"chladný",en:"cool"},
  {cz:"chlapce",en:"boy"},
  {cz:"chlapci",en:"boys"},
  {cz:"chlapců",en:"boys"},
  {cz:"chlapec",en:"boy"},
  {cz:"chléb",en:"bread"},
  {cz:"chodit",en:"go"},
  {cz:"chtít",en:"want"},
  {cz:"chudý",en:"poor"},
  {cz:"chutné",en:"delicious"},
  {cz:"chvět se",en:"to blush"},
  {cz:"chybět",en:"to miss"},
  {cz:"chytit",en:"to catch"},
  {cz:"chytrý",en:"smart"},
  {cz:"chápat",en:"understand"},
  {cz:"citrónový čaj",en:"lemon tea"},
  {cz:"cizinec",en:"foreigner"},
  {cz:"cizinka",en:"foreigner"},
  {cz:"co",en:"what"},
  {cz:"cukr",en:"sugar"},
  {cz:"cukrovka",en:"diabetes"},
  {cz:"cvičit",en:"to practice; to exercise"},
  {cz:"cíl",en:"target"},
  {cz:"cítit",en:"to feel"},
  {cz:"daleko",en:"far"},
  {cz:"daleko od",en:"away from"},
  {cz:"dalekohled",en:"telescope"},
  {cz:"další",en:"next"},
  {cz:"dcera",en:"daughter's"},
  {cz:"deka",en:"blanket"},
  {cz:"den",en:"day"},
  {cz:"den svatého Valentýna",en:"Valentine&#x27;s day"},
  {cz:"denní program",en:"agenda"},
  {cz:"deset",en:"ten"},
  {cz:"deset tisíc",en:"ten thousand"},
  {cz:"desátý",en:"tenth"},
  {cz:"detaily",en:"details"},
  {cz:"devadesát",en:"ninety"},
  {cz:"devatenáct",en:"nineteen"},
  {cz:"devatenáctý",en:"nineteenth"},
  {cz:"devátý",en:"ninth"},
  {cz:"devíti",en:"nine"},
  {cz:"devět",en:"nine"},
  {cz:"devět set",en:"nine hundred"},
  {cz:"dezert",en:"dessert"},
  {cz:"deštník",en:"umbrella"},
  {cz:"diamant",en:"diamond"},
  {cz:"divadlo",en:"theater"},
  {cz:"dlouho",en:"long"},
  {cz:"dlouhé rukávy",en:"long sleeves"},
  {cz:"dlouhý",en:"long"},
  {cz:"dnes",en:"today"},
  {cz:"dny",en:"days"},
  {cz:"dní",en:"days"},
  {cz:"do",en:"till"},
  {cz:"do zahraničí",en:"abroad"},
  {cz:"dobrodružství",en:"adventure"},
  {cz:"dobrou",en:"good"},
  {cz:"dobrá",en:"good"},
  {cz:"dobrá kondice",en:"fit"},
  {cz:"dobré",en:"good"},
  {cz:"dobrý",en:"good"},
  {cz:"dobrý den",en:"good morning"},
  {cz:"dobře",en:"well"},
  {cz:"dobře vypadající",en:"good looking"},
  {cz:"dodat",en:"to promote"},
  {cz:"dohlížet",en:"to look after"},
  {cz:"dokončit",en:"to finish"},
  {cz:"dokončit kurz",en:"to finish class"},
  {cz:"doktor",en:"doctor"},
  {cz:"dokázat",en:"to prove"},
  {cz:"doma",en:"at home"},
  {cz:"domnívat se",en:"to suppose"},
  {cz:"domov",en:"home"},
  {cz:"domy",en:"houses"},
  {cz:"domácí úkol",en:"homework"},
  {cz:"domů",en:"houses"},
  {cz:"dopis",en:"letter"},
  {cz:"doporučit",en:"to recommend"},
  {cz:"dost",en:"enough"},
  {cz:"dostat",en:"get"},
  {cz:"dostat se na",en:"to get on"},
  {cz:"dosáhnout",en:"to achieve"},
  {cz:"dotýkat se",en:"to touch"},
  {cz:"dovednosti",en:"skills"},
  {cz:"dovolená",en:"vacation"},
  {cz:"drahokam",en:"gem"},
  {cz:"drahý",en:"dear"},
  {cz:"drama",en:"drama"},
  {cz:"druhé",en:"second"},
  {cz:"druhý",en:"other"},
  {cz:"družice",en:"satellite"},
  {cz:"držet",en:"hold"},
  {cz:"držet za ruce",en:"to hold hands"},
  {cz:"duben",en:"April"},
  {cz:"duch",en:"ghost"},
  {cz:"dusit",en:"to steam"},
  {cz:"dva",en:"two"},
  {cz:"dvacet",en:"twenty"},
  {cz:"dvacet pět",en:"twenty-five"},
  {cz:"dvanáct",en:"twelve"},
  {cz:"dveře",en:"door"},
  {cz:"dvořák",en:"Dvořák"},
  {cz:"dvořáka",en:"Dvořák"},
  {cz:"dvořákovou",en:"Dvořáková"},
  {cz:"dvořáková",en:"Dvořáková"},
  {cz:"dvořáku",en:"Dvořák"},
  {cz:"dvě",en:"two"},
  {cz:"dvě stě",en:"two hundred"},
  {cz:"dárek",en:"present"},
  {cz:"dáseň",en:"gums"},
  {cz:"dát",en:"to put; to give; to lay"},
  {cz:"dávat přednost",en:"to prefer"},
  {cz:"déšť",en:"the rain"},
  {cz:"díky",en:"thanks"},
  {cz:"dítě",en:"child"},
  {cz:"dívat",en:"watch"},
  {cz:"dívka",en:"girl"},
  {cz:"dívku",en:"girl"},
  {cz:"dědeček",en:"grandpa's"},
  {cz:"děkuji",en:"thanks"},
  {cz:"děkuju",en:"Thank you"},
  {cz:"dělat",en:"makes"},
  {cz:"dělat pohovor",en:"to interview"},
  {cz:"děti",en:"children"},
  {cz:"dětí",en:"children"},
  {cz:"dřez",en:"sink"},
  {cz:"důležitý",en:"important"},
  {cz:"dům",en:"house"},
  {cz:"důvod",en:"reason"},
  {cz:"džungle",en:"jungle"},
  {cz:"džus",en:"juice"},
  {cz:"džíny",en:"jeans"},
  {cz:"e-mailem",en:"E-mail"},
  {cz:"esej",en:"essay"},
  {cz:"euro",en:"euro"},
  {cz:"existovat",en:"exist"},
  {cz:"fialová",en:"purple"},
  {cz:"flirtovat",en:"to flirt"},
  {cz:"fotbal",en:"soccer"},
  {cz:"fotbalový míč",en:"soccer"},
  {cz:"fotograf",en:"Photographer"},
  {cz:"františek",en:"František"},
  {cz:"františka",en:"František"},
  {cz:"františku",en:"František"},
  {cz:"galaxie",en:"galaxy"},
  {cz:"grilovat",en:"to grill"},
  {cz:"guma",en:"rubber"},
  {cz:"had",en:"snake"},
  {cz:"hadi",en:"snakes"},
  {cz:"hedvábí",en:"silk"},
  {cz:"herec",en:"Actor"},
  {cz:"hezká",en:"pretty"},
  {cz:"hezké",en:"pretty"},
  {cz:"hezký",en:"handsome"},
  {cz:"hlad",en:"hunger"},
  {cz:"hladký",en:"smooth"},
  {cz:"hlas",en:"voice"},
  {cz:"hlava",en:"head"},
  {cz:"hledat",en:"look for"},
  {cz:"hloupý",en:"stupid"},
  {cz:"hluboký",en:"deep"},
  {cz:"hnědá",en:"brown"},
  {cz:"hnědý",en:"brown"},
  {cz:"ho",en:"him"},
  {cz:"hodina",en:"hour"},
  {cz:"hodinky",en:"watch"},
  {cz:"hodně",en:"a lot"},
  {cz:"holka",en:"girl"},
  {cz:"holky",en:"girl"},
  {cz:"hora",en:"mountain"},
  {cz:"horečka",en:"fever"},
  {cz:"horké prameny",en:"hot spring"},
  {cz:"horký",en:"hot"},
  {cz:"horor",en:"horror"},
  {cz:"host",en:"guest"},
  {cz:"hotel",en:"hotel"},
  {cz:"hotely",en:"hotels"},
  {cz:"housle",en:"violin"},
  {cz:"hořké",en:"bitter"},
  {cz:"hrad",en:"castle"},
  {cz:"hrnec",en:"pot"},
  {cz:"hrubý",en:"rough"},
  {cz:"hruška",en:"pear"},
  {cz:"hrušky",en:"pears"},
  {cz:"hrát",en:"to play"},
  {cz:"hubený",en:"cute"},
  {cz:"hudba",en:"music"},
  {cz:"hudební lekce",en:"music class"},
  {cz:"hudební nástroje",en:"musical instruments"},
  {cz:"hudební škola",en:"music school"},
  {cz:"hudebník",en:"musician"},
  {cz:"hurikán",en:"hurricane"},
  {cz:"husa",en:"goose"},
  {cz:"hvězdy",en:"stars"},
  {cz:"hádat",en:"to guess"},
  {cz:"hádat se",en:"to argue"},
  {cz:"i",en:"and also"},
  {cz:"i když",en:"though"},
  {cz:"imigrační formulář",en:"immigration form"},
  {cz:"Internet",en:"Internet"},
  {cz:"inženýr",en:"Engineer"},
  {cz:"jablečný džus",en:"apple juice"},
  {cz:"jablka",en:"apples"},
  {cz:"jablko",en:"apple"},
  {cz:"jahoda",en:"a strawberry"},
  {cz:"jak",en:"how"},
  {cz:"jako",en:"as"},
  {cz:"jakub",en:"Jakub"},
  {cz:"jakube",en:"Jakub"},
  {cz:"jaký",en:"like"},
  {cz:"Japonsko",en:"Japan"},
  {cz:"japonština",en:"Japanese"},
  {cz:"jaro",en:"spring"},
  {cz:"jasný",en:"clearly; bright"},
  {cz:"jazz",en:"Jazz"},
  {cz:"je",en:"is"},
  {cz:"jeden",en:"one"},
  {cz:"jedenáct",en:"eleven"},
  {cz:"jedenáctý",en:"eleventh"},
  {cz:"jedna",en:"one"},
  {cz:"jedno",en:"one"},
  {cz:"jednolůžkový pokoj",en:"a single room"},
  {cz:"jedné",en:"one"},
  {cz:"jeho",en:"him"},
  {cz:"jej",en:"him"},
  {cz:"jejich",en:"their"},
  {cz:"její",en:"her"},
  {cz:"jejích",en:"her"},
  {cz:"jejího",en:"her"},
  {cz:"jen",en:"only"},
  {cz:"jestli",en:"if"},
  {cz:"jet",en:"travel"},
  {cz:"jezdící schody",en:"escalator"},
  {cz:"jezero",en:"lake"},
  {cz:"ještě",en:"yet"},
  {cz:"ji",en:"her"},
  {cz:"jich",en:"them"},
  {cz:"jih",en:"south"},
  {cz:"jinam",en:"somewhere else"},
  {cz:"jinde",en:"elsewhere"},
  {cz:"jiný",en:"other"},
  {cz:"jitka",en:"Jitka"},
  {cz:"jitko",en:"Jitka"},
  {cz:"jitku",en:"Jitka"},
  {cz:"jmenuje",en:"is named"},
  {cz:"jmenujete",en:"your name is"},
  {cz:"jmenuješ",en:"name"},
  {cz:"jmenujou",en:"name"},
  {cz:"jmenuju",en:"name"},
  {cz:"jména",en:"name"},
  {cz:"jméno",en:"name"},
  {cz:"jsem",en:"am"},
  {cz:"jsi",en:"are you"},
  {cz:"jsme",en:"haven't"},
  {cz:"jsou",en:"is"},
  {cz:"jste",en:"are you"},
  {cz:"já",en:"I"},
  {cz:"jí",en:"her"},
  {cz:"jídlo",en:"food"},
  {cz:"jíst",en:"eating"},
  {cz:"jít",en:"haven't"},
  {cz:"jít na rande",en:"to go on a date"},
  {cz:"jít pěšky",en:"to walk"},
  {cz:"jít rovně",en:"to go straight"},
  {cz:"jít ven",en:"to go out"},
  {cz:"jízdenka na autobus",en:"a bus ticket"},
  {cz:"jízdenka na vlak",en:"a train ticket"},
  {cz:"jízdní kolo",en:"a bicycle"},
  {cz:"jízdní řád",en:"a schedule"},
  {cz:"jóga",en:"yoga"},
  {cz:"kabát",en:"coat"},
  {cz:"kachna",en:"duck"},
  {cz:"kalhoty",en:"pants"},
  {cz:"kam",en:"where"},
  {cz:"kancelář",en:"agency"},
  {cz:"kantýna",en:"a cafeteria"},
  {cz:"kapela",en:"band"},
  {cz:"kateřina",en:"Kateřina"},
  {cz:"kateřino",en:"Kateřina"},
  {cz:"kateřinu",en:"Kateřina"},
  {cz:"kateřiny",en:"Kateřina's"},
  {cz:"kavárna",en:"a coffee shop"},
  {cz:"každou",en:"every"},
  {cz:"každé",en:"each"},
  {cz:"každý",en:"each"},
  {cz:"každý den",en:"every day"},
  {cz:"kde",en:"where"},
  {cz:"kdežto",en:"whereas"},
  {cz:"kdo",en:"who"},
  {cz:"kdy",en:"when"},
  {cz:"když",en:"while"},
  {cz:"kilogram",en:"kilogram"},
  {cz:"klasický",en:"Classic"},
  {cz:"klavír",en:"piano"},
  {cz:"klimatizace",en:"air-conditioner"},
  {cz:"klobouk",en:"hat"},
  {cz:"kluci",en:"boys"},
  {cz:"kluk",en:"boy"},
  {cz:"klíč od pokoje",en:"a room key"},
  {cz:"kniha",en:"book"},
  {cz:"knihkupectví",en:"a book store"},
  {cz:"knihovna",en:"library"},
  {cz:"knihy",en:"book"},
  {cz:"koho",en:"whom"},
  {cz:"koktejl",en:"a smoothie"},
  {cz:"kolega",en:"colleague"},
  {cz:"kolem",en:"about"},
  {cz:"kolik",en:"how many"},
  {cz:"kolika",en:"how many"},
  {cz:"kolo",en:"bicycle"},
  {cz:"komedie",en:"comedy"},
  {cz:"komentovat",en:"to comment"},
  {cz:"komora",en:"storage room"},
  {cz:"kontaktovat",en:"to contact"},
  {cz:"konvice",en:"pot; kettle"},
  {cz:"konzultant",en:"consultant"},
  {cz:"končit",en:"to finish"},
  {cz:"koriandr",en:"cilantro"},
  {cz:"koruna",en:"crown"},
  {cz:"kosmická loď",en:"spaceship"},
  {cz:"kost",en:"bone"},
  {cz:"koule",en:"sphere"},
  {cz:"koupelna",en:"bathroom"},
  {cz:"koupit",en:"buy"},
  {cz:"koza",en:"goat"},
  {cz:"kozy",en:"goats"},
  {cz:"kočka",en:"cat"},
  {cz:"kočky",en:"cat"},
  {cz:"košile",en:"shirt"},
  {cz:"košík",en:"basket"},
  {cz:"kožené boty",en:"leather shoes"},
  {cz:"krabice",en:"a box"},
  {cz:"kreditni karta",en:"a credit card"},
  {cz:"kreslit",en:"to draw"},
  {cz:"krev",en:"blood"},
  {cz:"krk",en:"neck"},
  {cz:"kruh",en:"circle"},
  {cz:"krychle",en:"cube"},
  {cz:"krádež",en:"stealing"},
  {cz:"krásný",en:"beautiful"},
  {cz:"krátké rukávy",en:"short sleeves"},
  {cz:"krátký",en:"brief"},
  {cz:"kráva",en:"cow"},
  {cz:"který",en:"that"},
  {cz:"kuchař",en:"cook"},
  {cz:"kuchyně",en:"cuisine"},
  {cz:"kudrnatý",en:"curly"},
  {cz:"kupovat",en:"buy"},
  {cz:"kurz",en:"class"},
  {cz:"kuřata",en:"chickens"},
  {cz:"kuře",en:"chicken"},
  {cz:"kuřecí",en:"chicken"},
  {cz:"květ",en:"flower"},
  {cz:"květen",en:"May"},
  {cz:"kyselé",en:"sour"},
  {cz:"kytara",en:"guitar"},
  {cz:"kytice",en:"bouquet"},
  {cz:"káva",en:"coffee"},
  {cz:"křeslo",en:"a chair"},
  {cz:"křižovatka",en:"intersection"},
  {cz:"kůň",en:"horse"},
  {cz:"kůže",en:"skin"},
  {cz:"led",en:"ice"},
  {cz:"leden",en:"January"},
  {cz:"lednička",en:"fridge"},
  {cz:"ledová káva",en:"iced coffee"},
  {cz:"legrační",en:"funny"},
  {cz:"lehký",en:"light"},
  {cz:"lesní požár",en:"forest fire"},
  {cz:"let",en:"a flight"},
  {cz:"letadlo",en:"an airplane"},
  {cz:"letecká pošta",en:"mail"},
  {cz:"letenka",en:"a plane ticket"},
  {cz:"letiště",en:"airport"},
  {cz:"levný",en:"inexpensive"},
  {cz:"levý",en:"left"},
  {cz:"ležet",en:"lie"},
  {cz:"lhát",en:"to lie"},
  {cz:"lidé",en:"people"},
  {cz:"linka",en:"line"},
  {cz:"listopad",en:"November"},
  {cz:"liška",en:"fox"},
  {cz:"ložnice",en:"bedroom"},
  {cz:"lupič",en:"burglar"},
  {cz:"láhev",en:"bottle"},
  {cz:"lék",en:"medicine"},
  {cz:"léky",en:"medicine"},
  {cz:"lékárna",en:"pharmacy"},
  {cz:"léto",en:"summer"},
  {cz:"léčba",en:"treatment"},
  {cz:"lístek",en:"a menu"},
  {cz:"lžíce",en:"spoon"},
  {cz:"malá",en:"little"},
  {cz:"malé",en:"little"},
  {cz:"malí",en:"small"},
  {cz:"malý",en:"small"},
  {cz:"malých",en:"little"},
  {cz:"manažer",en:"Manager"},
  {cz:"manžel",en:"spouse"},
  {cz:"manželka",en:"spouse"},
  {cz:"maso",en:"meat"},
  {cz:"matka",en:"mother"},
  {cz:"matěj",en:"Matěj"},
  {cz:"matěje",en:"Matěj"},
  {cz:"matěji",en:"Matěj"},
  {cz:"medvěd",en:"bear"},
  {cz:"meloun",en:"watermelon"},
  {cz:"metoda",en:"method"},
  {cz:"metro",en:"a subway"},
  {cz:"mezi",en:"between"},
  {cz:"mikrovlnná trouba",en:"microwave"},
  {cz:"milion",en:"a million"},
  {cz:"milovat",en:"love"},
  {cz:"mimo",en:"outside"},
  {cz:"mimozemšťan",en:"alien"},
  {cz:"mince",en:"coin"},
  {cz:"minulý měsíc",en:"last month"},
  {cz:"minulý rok",en:"last year"},
  {cz:"minuta",en:"minute"},
  {cz:"minutu",en:"a minute"},
  {cz:"mladou",en:"young"},
  {cz:"mladá",en:"young"},
  {cz:"mladé",en:"young"},
  {cz:"mladého",en:"young"},
  {cz:"mladý",en:"young"},
  {cz:"mladší bratr",en:"younger brother"},
  {cz:"mladší sestra",en:"younger sister"},
  {cz:"mluvit",en:"haven't"},
  {cz:"mluvíte",en:"do you speak"},
  {cz:"mléka",en:"milk"},
  {cz:"mléko",en:"milk"},
  {cz:"mnoho",en:"many"},
  {cz:"mobilní telefon",en:"mobile phone"},
  {cz:"moci",en:"can"},
  {cz:"modrá",en:"blue"},
  {cz:"modrý",en:"blue"},
  {cz:"moje",en:"my"},
  {cz:"moji",en:"my"},
  {cz:"mojí",en:"my"},
  {cz:"most",en:"bridge"},
  {cz:"motocykl",en:"a motorcycle"},
  {cz:"mou",en:"my"},
  {cz:"moucha",en:"fly"},
  {cz:"mořské plody",en:"seafood"},
  {cz:"možná",en:"maybe"},
  {cz:"možný",en:"possible"},
  {cz:"mražené",en:"frozen"},
  {cz:"mrkev",en:"carrot"},
  {cz:"mrkve",en:"carrots"},
  {cz:"mrtvý",en:"dead"},
  {cz:"mrznout",en:"freezing"},
  {cz:"muzeum",en:"a museum"},
  {cz:"muž",en:"man"},
  {cz:"muže",en:"husband"},
  {cz:"muži",en:"husband"},
  {cz:"my",en:"we"},
  {cz:"myslet",en:"think"},
  {cz:"myš",en:"mouse"},
  {cz:"myši",en:"mice"},
  {cz:"má",en:"he has"},
  {cz:"málo",en:"little"},
  {cz:"máma",en:"mom"},
  {cz:"mámy",en:"moms"},
  {cz:"máta",en:"mint"},
  {cz:"mé",en:"my"},
  {cz:"mého",en:"my"},
  {cz:"mém",en:"my"},
  {cz:"mí",en:"my"},
  {cz:"místnost",en:"room"},
  {cz:"místo",en:"site"},
  {cz:"místo setkání",en:"meeting point"},
  {cz:"mít",en:"haven't"},
  {cz:"mít rád",en:"to like"},
  {cz:"mít zlomené srdce",en:"to be heartbroken"},
  {cz:"míč",en:"ball"},
  {cz:"mých",en:"my"},
  {cz:"mýdlo",en:"soap"},
  {cz:"mě",en:"me"},
  {cz:"měkký",en:"soft"},
  {cz:"měna",en:"currency"},
  {cz:"města",en:"city's"},
  {cz:"město",en:"city"},
  {cz:"měsíc",en:"moon"},
  {cz:"měsíci",en:"month"},
  {cz:"můj",en:"my"},
  {cz:"na",en:"onto"},
  {cz:"na rohu",en:"at the corner"},
  {cz:"na shledanou",en:"goodbye"},
  {cz:"najmout",en:"to hire"},
  {cz:"najít",en:"locate"},
  {cz:"nakupovat",en:"to shop"},
  {cz:"nalevo",en:"on the left"},
  {cz:"napravo",en:"on the right"},
  {cz:"naproti",en:"opposite to"},
  {cz:"napsat",en:"write"},
  {cz:"narozeniny",en:"birthday"},
  {cz:"nastoupit",en:"to board"},
  {cz:"nastoupit do autobusu",en:"to get on the bus"},
  {cz:"natřít",en:"to paint"},
  {cz:"navrhnout",en:"to suggest"},
  {cz:"navštívit",en:"to visit"},
  {cz:"navštívit lékaře",en:"to see the doctor"},
  {cz:"navždy",en:"forever"},
  {cz:"naše",en:"our"},
  {cz:"našeho",en:"our"},
  {cz:"našem",en:"our"},
  {cz:"naši",en:"our"},
  {cz:"našich",en:"our"},
  {cz:"naší",en:"our"},
  {cz:"ne",en:"no"},
  {cz:"nebe",en:"sky"},
  {cz:"nebezpečný",en:"dangerous"},
  {cz:"nebo",en:"or"},
  {cz:"nebyl",en:"haven't"},
  {cz:"nebyla",en:"haven't"},
  {cz:"nebylas",en:"you were not"},
  {cz:"nebyli",en:"haven't"},
  {cz:"nebylo",en:"haven't"},
  {cz:"nebyls",en:"you were not"},
  {cz:"nebyly",en:"haven't"},
  {cz:"nechat si ujít",en:"to miss"},
  {cz:"nedívat",en:"not to look"},
  {cz:"neděle",en:"Sundays"},
  {cz:"nefrit",en:"jade"},
  {cz:"nehoda",en:"accident"},
  {cz:"nejdřív",en:"first"},
  {cz:"nejí",en:"she doesn\\'t eat"},
  {cz:"nejíst",en:"doesn\\'t"},
  {cz:"nemocnice",en:"hospital"},
  {cz:"nemocný",en:"sick"},
  {cz:"nemyslet",en:"didn\\'t"},
  {cz:"nemít",en:"haven't"},
  {cz:"nenávidět",en:"hate"},
  {cz:"není",en:"n't"},
  {cz:"nepotřebovat",en:"doesn\\'t"},
  {cz:"nepoznávat",en:"didn\\'t"},
  {cz:"nepít",en:"doesn\\'t"},
  {cz:"nerozumím",en:"I don't understand"},
  {cz:"neslyšet",en:"haven't"},
  {cz:"neslyší",en:"does not hear"},
  {cz:"neteř",en:"Niece"},
  {cz:"nevidí",en:"does not see"},
  {cz:"nevidíš",en:"(you) do not see"},
  {cz:"nevidět",en:"haven't"},
  {cz:"nevinný",en:"innocent"},
  {cz:"nezajímat",en:"doesn\\'t"},
  {cz:"nezaměstnaný",en:"unemployed"},
  {cz:"nezbytné",en:"necessary"},
  {cz:"neznat",en:"haven't"},
  {cz:"nečekat",en:"haven't"},
  {cz:"nešťastný",en:"unhappy"},
  {cz:"ni",en:"her"},
  {cz:"nich",en:"(about) them"},
  {cz:"nikam",en:"anywhere"},
  {cz:"nikde",en:"nowhere"},
  {cz:"nikdy",en:"never"},
  {cz:"noc",en:"night"},
  {cz:"noci",en:"night"},
  {cz:"noha",en:"foot"},
  {cz:"nos",en:"nose"},
  {cz:"nosit",en:"wear"},
  {cz:"nouzový",en:"emergency"},
  {cz:"nouzový východ",en:"emergency exit"},
  {cz:"noviny",en:"newspaper"},
  {cz:"novinář",en:"Journalist"},
  {cz:"novotnou",en:"Novotná"},
  {cz:"novotná",en:"(female surname)"},
  {cz:"novotného",en:"Novotný"},
  {cz:"novotný",en:"Novotný"},
  {cz:"nová",en:"new"},
  {cz:"nové",en:"new"},
  {cz:"nový",en:"new"},
  {cz:"Nový rok",en:"New Year&#x27;s Day"},
  {cz:"nudný",en:"boring"},
  {cz:"nyní",en:"now"},
  {cz:"nádraží",en:"station"},
  {cz:"náhrdelník",en:"necklace"},
  {cz:"náměstí",en:"square"},
  {cz:"nápad",en:"idea"},
  {cz:"nápoj",en:"drink"},
  {cz:"náramek",en:"bracelet"},
  {cz:"nás",en:"us"},
  {cz:"následovat",en:"to follow"},
  {cz:"náušnice",en:"earrings"},
  {cz:"názor",en:"opinion"},
  {cz:"náš",en:"our"},
  {cz:"nést",en:"to carry"},
  {cz:"ní",en:"her"},
  {cz:"nízký",en:"low"},
  {cz:"ně",en:"them"},
  {cz:"něho",en:"him"},
  {cz:"něj",en:"him"},
  {cz:"někam",en:"somewhere"},
  {cz:"někde",en:"somewhere"},
  {cz:"někdy",en:"sometimes"},
  {cz:"něm",en:"him"},
  {cz:"Německo",en:"Germany"},
  {cz:"němčina",en:"German"},
  {cz:"nůž",en:"knife"},
  {cz:"o",en:"for"},
  {cz:"obchod",en:"shop"},
  {cz:"Obchody s obuví",en:"Shoe store"},
  {cz:"obdélník",en:"rectangle"},
  {cz:"objednat",en:"to order"},
  {cz:"oblek",en:"suit"},
  {cz:"oblečení",en:"clothing"},
  {cz:"obličej",en:"face"},
  {cz:"obloha",en:"sky"},
  {cz:"obléci si",en:"to put on"},
  {cz:"oblíbený",en:"favourite"},
  {cz:"obnovit",en:"to renew"},
  {cz:"obrázek",en:"picture"},
  {cz:"obtížný",en:"difficult"},
  {cz:"obviněný",en:"defendant"},
  {cz:"obálka",en:"envelope"},
  {cz:"obývací pokoj",en:"living room"},
  {cz:"obývák",en:"living room"},
  {cz:"oběd",en:"lunch"},
  {cz:"oběť",en:"victim"},
  {cz:"oběžná dráha",en:"orbit"},
  {cz:"oceán",en:"ocean"},
  {cz:"od",en:"since"},
  {cz:"odbočit doleva",en:"to turn left"},
  {cz:"odbočit doprava",en:"to turn right"},
  {cz:"odhlášení z hotelu",en:"check-out"},
  {cz:"odjet",en:"to depart"},
  {cz:"odkud",en:"where...from"},
  {cz:"odpoledne",en:"afternoon"},
  {cz:"odpovědět",en:"to reply; to answer"},
  {cz:"odpočívat",en:"to rest"},
  {cz:"odpustit",en:"to forgive"},
  {cz:"Oheň!",en:"Fire!"},
  {cz:"ohlásit",en:"to report"},
  {cz:"ohřát",en:"to heat"},
  {cz:"okno",en:"window"},
  {cz:"oko",en:"eye"},
  {cz:"okouzlující",en:"charming"},
  {cz:"oloupat",en:"to peel"},
  {cz:"omluvit se",en:"to apologize"},
  {cz:"omáčka",en:"sauce"},
  {cz:"on",en:"he"},
  {cz:"ona",en:"she"},
  {cz:"oni",en:"they"},
  {cz:"ono",en:"it"},
  {cz:"ony",en:"they"},
  {cz:"opakovat",en:"to repeat"},
  {cz:"operace",en:"operation"},
  {cz:"opice",en:"monkey"},
  {cz:"oprava bot",en:"shoe repair store"},
  {cz:"opravdu",en:"really"},
  {cz:"opravit",en:"to repair; to fix"},
  {cz:"oranžová",en:"orange"},
  {cz:"osel",en:"donkey"},
  {cz:"oslava",en:"celebration"},
  {cz:"oslava nového bytu",en:"Housewarming"},
  {cz:"osm",en:"eight"},
  {cz:"osm set",en:"eight hundred"},
  {cz:"osmdesát",en:"eighty"},
  {cz:"osmnáct",en:"eighteen"},
  {cz:"osmý",en:"eighth"},
  {cz:"osoba",en:"person"},
  {cz:"osoby",en:"people"},
  {cz:"osprchovat se",en:"to shower"},
  {cz:"ostrov",en:"island"},
  {cz:"otec",en:"father"},
  {cz:"otevřený",en:"open"},
  {cz:"otevřít",en:"to open"},
  {cz:"otevřít ústa",en:"to open one&#x27;s mouth"},
  {cz:"otrava jídlem",en:"food poisoning"},
  {cz:"otázka",en:"question"},
  {cz:"ovce",en:"sheep"},
  {cz:"ovoce",en:"fruit"},
  {cz:"ovocný džus",en:"fruit juice"},
  {cz:"ozdobit",en:"to decorate"},
  {cz:"označit",en:"to tag"},
  {cz:"oči",en:"eyes"},
  {cz:"ošklivý",en:"ugly"},
  {cz:"pacient",en:"patient"},
  {cz:"padesát",en:"fifty"},
  {cz:"padnout",en:"to fit"},
  {cz:"palubní vstupenka",en:"boarding pass"},
  {cz:"pamatovat",en:"remember"},
  {cz:"pamatovat si",en:"to remember"},
  {cz:"pan",en:"Mr."},
  {cz:"pana",en:"Mr."},
  {cz:"pane",en:"Mr."},
  {cz:"panenka",en:"doll"},
  {cz:"panika",en:"panic"},
  {cz:"paní",en:"ma'am"},
  {cz:"papír",en:"paper"},
  {cz:"park",en:"a park"},
  {cz:"patnáct",en:"fifteen"},
  {cz:"patnáctý",en:"fifteenth"},
  {cz:"patro",en:"floor"},
  {cz:"pavouk",en:"spider"},
  {cz:"paže",en:"arm"},
  {cz:"peníze",en:"money"},
  {cz:"peněženka",en:"wallet"},
  {cz:"pepř",en:"pepper"},
  {cz:"pera",en:"pens"},
  {cz:"perfektní",en:"perfect"},
  {cz:"perla",en:"pearl"},
  {cz:"pero",en:"pen"},
  {cz:"personální oddělení",en:"human resource"},
  {cz:"pes",en:"dog"},
  {cz:"pečovat",en:"to take care"},
  {cz:"piji",en:"I drink"},
  {cz:"pijí",en:"drink"},
  {cz:"pivo",en:"beer"},
  {cz:"pizza",en:"pizza"},
  {cz:"plakat",en:"crying"},
  {cz:"planeta",en:"planet"},
  {cz:"plat",en:"salary"},
  {cz:"platit",en:"to pay"},
  {cz:"plavat",en:"swimming"},
  {cz:"plechovka",en:"a can"},
  {cz:"plný",en:"full"},
  {cz:"plánovat",en:"to plan"},
  {cz:"pláštěnka",en:"raincoat"},
  {cz:"pláž",en:"beach"},
  {cz:"po",en:"for"},
  {cz:"pod",en:"under"},
  {cz:"podezřelý",en:"suspect"},
  {cz:"podivný",en:"strange"},
  {cz:"podnikatel",en:"Businessman"},
  {cz:"podrážka boty",en:"sole"},
  {cz:"podvádět",en:"to cheat"},
  {cz:"podzim",en:"fall"},
  {cz:"pohlednice",en:"postcard"},
  {cz:"pohledný",en:"handsome"},
  {cz:"pohovka",en:"sofa"},
  {cz:"pokoj",en:"peace"},
  {cz:"pokoj pro dva",en:"a double room"},
  {cz:"pokojská",en:"maid"},
  {cz:"pokračovat",en:"to continue"},
  {cz:"pokrok",en:"progress"},
  {cz:"pokud",en:"if"},
  {cz:"policie",en:"police"},
  {cz:"policista",en:"Police officer"},
  {cz:"položit",en:"to put"},
  {cz:"polévka",en:"soup"},
  {cz:"polštář",en:"pillow"},
  {cz:"pomalu",en:"slowly"},
  {cz:"pomalý",en:"slow"},
  {cz:"pomeranč",en:"orange"},
  {cz:"pomeranče",en:"orange"},
  {cz:"Pomoc!",en:"Help!"},
  {cz:"pomoci",en:"to help"},
  {cz:"poměr",en:"affair"},
  {cz:"pondělí",en:"Mondays"},
  {cz:"ponožka",en:"sock"},
  {cz:"ponožky",en:"socks"},
  {cz:"pop",en:"Pop"},
  {cz:"popsat",en:"to describe"},
  {cz:"popřít",en:"to deny"},
  {cz:"porovnat",en:"to compare to"},
  {cz:"poslat",en:"to send"},
  {cz:"poslat zprávu",en:"to send a message"},
  {cz:"poslat žádost o přítele",en:"to send a friend request"},
  {cz:"poslední",en:"last"},
  {cz:"poslouchat",en:"listen"},
  {cz:"pospěš si",en:"hurry"},
  {cz:"postavit",en:"to build"},
  {cz:"postel",en:"bed"},
  {cz:"postele",en:"bed"},
  {cz:"postovat",en:"to post"},
  {cz:"potit se",en:"to sweat"},
  {cz:"potkat",en:"to meet"},
  {cz:"potom",en:"then"},
  {cz:"potřebovat",en:"require"},
  {cz:"poušť",en:"desert"},
  {cz:"použít",en:"to use"},
  {cz:"považovat",en:"consider"},
  {cz:"povolit",en:"to allow"},
  {cz:"povýšení",en:"promotion"},
  {cz:"povýšit",en:"to promote"},
  {cz:"pozdě",en:"late"},
  {cz:"poznámky",en:"minutes"},
  {cz:"poznávám",en:"meet"},
  {cz:"pozornost",en:"attention"},
  {cz:"pozorovat",en:"to stargaze"},
  {cz:"pozvat",en:"to invite"},
  {cz:"pozvánka",en:"Invitation letter"},
  {cz:"počasí",en:"weather"},
  {cz:"počkat",en:"to wait"},
  {cz:"počítat",en:"count"},
  {cz:"počítač",en:"computer"},
  {cz:"pořídit fotku",en:"to take photos"},
  {cz:"poškodit",en:"to damage"},
  {cz:"pošta",en:"post office"},
  {cz:"požádat o ruku",en:"to propose"},
  {cz:"pracovat",en:"work"},
  {cz:"prarodiče",en:"Grandparents"},
  {cz:"prasata",en:"pigs"},
  {cz:"prase",en:"pig"},
  {cz:"PRAVDA",en:"the truth"},
  {cz:"pravý",en:"right"},
  {cz:"pračka",en:"washing machine"},
  {cz:"pro",en:"for"},
  {cz:"problém",en:"problem"},
  {cz:"prodat",en:"to sell"},
  {cz:"prodejce vstupenek",en:"a ticket seller"},
  {cz:"prodávat",en:"sell"},
  {cz:"profesor",en:"Professor"},
  {cz:"profil",en:"profile"},
  {cz:"prohlížení památek",en:"sightseeing"},
  {cz:"projednat",en:"to discuss"},
  {cz:"projekt",en:"project"},
  {cz:"pronajmout",en:"to rent"},
  {cz:"propustit",en:"to fire"},
  {cz:"prosinec",en:"December"},
  {cz:"prosím",en:"please"},
  {cz:"proto",en:"because"},
  {cz:"protože",en:"because"},
  {cz:"proč",en:"why"},
  {cz:"prst",en:"finger"},
  {cz:"prsten",en:"ring"},
  {cz:"první",en:"first"},
  {cz:"pryč",en:"away"},
  {cz:"práce",en:"job"},
  {cz:"práce na plný úvazek",en:"full-time job"},
  {cz:"práce na částečný úvazek",en:"part-time job"},
  {cz:"prát",en:"wash"},
  {cz:"právník",en:"Lawyer"},
  {cz:"prázdný",en:"empty"},
  {cz:"prášek",en:"pill"},
  {cz:"prášky proti bolesti",en:"pain killer"},
  {cz:"pršet",en:"to rain"},
  {cz:"průjem",en:"diarrhea"},
  {cz:"průkaz totožnosti",en:"Personal ID card"},
  {cz:"průměr",en:"diameter"},
  {cz:"průvodce",en:"guide"},
  {cz:"psi",en:"dogs"},
  {cz:"psát",en:"write"},
  {cz:"ptáci",en:"birds"},
  {cz:"pták",en:"bird"},
  {cz:"ptát",en:"ask"},
  {cz:"pálivé",en:"spicy"},
  {cz:"pánev",en:"pan"},
  {cz:"párky",en:"sausage"},
  {cz:"pásek",en:"belt"},
  {cz:"pásový dopravník",en:"conveyor belt"},
  {cz:"pátek",en:"Friday"},
  {cz:"pátý",en:"fifth"},
  {cz:"péct",en:"to bake"},
  {cz:"píseň",en:"song"},
  {cz:"pít",en:"drink"},
  {cz:"pět",en:"five"},
  {cz:"pět set",en:"five hundred"},
  {cz:"před",en:"in front of; before"},
  {cz:"předložit",en:"to present"},
  {cz:"předpis",en:"prescription"},
  {cz:"předpovídat",en:"to forecast"},
  {cz:"představit si",en:"to imagine"},
  {cz:"přejít",en:"to cross"},
  {cz:"přerušovat",en:"to interrupt"},
  {cz:"přestat",en:"to stop"},
  {cz:"přestat sledovat",en:"to unfollow"},
  {cz:"přesto",en:"yet"},
  {cz:"přestože",en:"although"},
  {cz:"přestávka",en:"a break"},
  {cz:"převést",en:"to transfer"},
  {cz:"přezkoumat",en:"to review"},
  {cz:"přečíst",en:"read"},
  {cz:"při",en:"at"},
  {cz:"přidat",en:"to put"},
  {cz:"přihlášení na hotel",en:"check-in"},
  {cz:"přijet",en:"to arrive"},
  {cz:"přijít",en:"comes"},
  {cz:"přinést",en:"to have (to get)"},
  {cz:"připojit se",en:"to join"},
  {cz:"připomínat",en:"to remind"},
  {cz:"přistát",en:"to land"},
  {cz:"přistýlka",en:"extra bed"},
  {cz:"přiznat",en:"to confess"},
  {cz:"přiznat si",en:"to admit"},
  {cz:"přát si",en:"to wish"},
  {cz:"přátelé",en:"friends"},
  {cz:"příbuzní",en:"Relatives"},
  {cz:"příběh",en:"story"},
  {cz:"příjmení",en:"last name"},
  {cz:"příležitost",en:"opportunity"},
  {cz:"příliš",en:"too much"},
  {cz:"případ",en:"case"},
  {cz:"příroda",en:"nature"},
  {cz:"přístav",en:"harbor"},
  {cz:"přítel",en:"boyfriend's"},
  {cz:"přítelkyně",en:"girlfriend"},
  {cz:"příznak",en:"symptom"},
  {cz:"příští měsíc",en:"next month"},
  {cz:"půl",en:"half"},
  {cz:"radit",en:"to advise"},
  {cz:"raději",en:"like more"},
  {cz:"rajčata",en:"tomatoes"},
  {cz:"rajče",en:"tomato"},
  {cz:"raketa",en:"rocket"},
  {cz:"razítko",en:"stamp"},
  {cz:"recepce",en:"reception"},
  {cz:"regál",en:"bookshelf"},
  {cz:"renovovat",en:"to renovate"},
  {cz:"report",en:"report"},
  {cz:"respektovat",en:"respect"},
  {cz:"restaurace",en:"restaurants"},
  {cz:"restauraci",en:"restaurant"},
  {cz:"ret",en:"lip"},
  {cz:"rezervovat",en:"to reserve"},
  {cz:"rock",en:"Rock"},
  {cz:"rodina",en:"family"},
  {cz:"rodič",en:"parent"},
  {cz:"rodiče",en:"parents"},
  {cz:"rodné město",en:"hometown"},
  {cz:"rok",en:"year"},
  {cz:"romantický",en:"romantic"},
  {cz:"román",en:"novel"},
  {cz:"rovný",en:"straight"},
  {cz:"rozbít",en:"to break"},
  {cz:"rozejít se",en:"to separate; to break up"},
  {cz:"rozhodnout",en:"to decide"},
  {cz:"roztomilý",en:"cute"},
  {cz:"rozzlobený",en:"angry"},
  {cz:"ruka",en:"hand"},
  {cz:"rukavice",en:"glove"},
  {cz:"ryba",en:"fish"},
  {cz:"rychle",en:"quickly"},
  {cz:"rychlý",en:"fast"},
  {cz:"rád",en:"like"},
  {cz:"ráno",en:"morning"},
  {cz:"rýže",en:"rice"},
  {cz:"růst",en:"to grow"},
  {cz:"růžová",en:"pink"},
  {cz:"sama",en:"alone"},
  {cz:"sandály",en:"sandals"},
  {cz:"Saturn",en:"Saturn"},
  {cz:"schválit",en:"to approve"},
  {cz:"schůzka",en:"to hang out; meeting"},
  {cz:"se",en:"with"},
  {cz:"sedm",en:"seven"},
  {cz:"sedm ráno",en:"7 am"},
  {cz:"sedm set",en:"seven hundred"},
  {cz:"sedmdesát",en:"seventy"},
  {cz:"sedmnáct",en:"seventeen"},
  {cz:"sedmnáctý",en:"seventeenth"},
  {cz:"sedmý",en:"seventh"},
  {cz:"sednout",en:"to sit"},
  {cz:"sedět",en:"sit"},
  {cz:"sekat",en:"to chop"},
  {cz:"sekretářka",en:"Secretary"},
  {cz:"selhat",en:"to fail"},
  {cz:"sem",en:"here"},
  {cz:"semafor",en:"a traffic light"},
  {cz:"ses",en:"part of reflexive verb"},
  {cz:"sestra",en:"sister's"},
  {cz:"sestřenice",en:"cousins"},
  {cz:"sesuv půdy",en:"mudslide"},
  {cz:"sever",en:"north"},
  {cz:"sexy",en:"sexy"},
  {cz:"shrnout",en:"to summarize"},
  {cz:"shromáždit",en:"to gather"},
  {cz:"si",en:"your"},
  {cz:"silnice",en:"road"},
  {cz:"silný",en:"strong"},
  {cz:"silně",en:"heavily"},
  {cz:"sis",en:"(reflexive pronoun)"},
  {cz:"sklenice",en:"glasses"},
  {cz:"skončit",en:"finish"},
  {cz:"skříň",en:"closet"},
  {cz:"slabý",en:"weak"},
  {cz:"sladké",en:"sweet"},
  {cz:"slané",en:"salty"},
  {cz:"slavit",en:"to celebrate"},
  {cz:"sledovat film",en:"to watch a movie"},
  {cz:"sledovat televizi",en:"to watch TV"},
  {cz:"sledující",en:"follower"},
  {cz:"slepice",en:"hen"},
  {cz:"sleva",en:"to discount"},
  {cz:"slib",en:"promise"},
  {cz:"slovník",en:"a dictionary"},
  {cz:"slovo",en:"word"},
  {cz:"slunce",en:"sun"},
  {cz:"sluneční brýle",en:"sunglasses"},
  {cz:"sluneční soustava",en:"solar system"},
  {cz:"slunný",en:"sunny"},
  {cz:"služební",en:"business"},
  {cz:"slyšet",en:"hear"},
  {cz:"slíbit",en:"to promise"},
  {cz:"smažená rýže",en:"fried rice"},
  {cz:"smažená vejce",en:"fried egg"},
  {cz:"smažit",en:"to fry"},
  {cz:"smlouva",en:"contract"},
  {cz:"smutný",en:"sad"},
  {cz:"smát se",en:"to laugh"},
  {cz:"směnný kurz",en:"exchange rate"},
  {cz:"snadný",en:"easy"},
  {cz:"snažit",en:"trying"},
  {cz:"snubní prsten",en:"wedding ring"},
  {cz:"snídaně",en:"breakfast"},
  {cz:"sníh",en:"the snow"},
  {cz:"sníst",en:"to eat"},
  {cz:"snít",en:"to dream"},
  {cz:"sněhová bouře",en:"snowstorm"},
  {cz:"sněžit",en:"to snow"},
  {cz:"sobota",en:"saturday"},
  {cz:"sopka",en:"volcano"},
  {cz:"soud",en:"court"},
  {cz:"soudce",en:"judge"},
  {cz:"souhlasit",en:"to agree"},
  {cz:"sourozenec",en:"sibling"},
  {cz:"Spojené státy americké",en:"USA"},
  {cz:"společnost",en:"Company"},
  {cz:"společný pokoj",en:"a shared room"},
  {cz:"spolu",en:"together"},
  {cz:"spolubydlící",en:"roommate"},
  {cz:"spolužák",en:"classmate"},
  {cz:"sport",en:"sport"},
  {cz:"sportovní obuv",en:"sports shoes"},
  {cz:"spáchat sebevraždu",en:"to commit suicide"},
  {cz:"spát",en:"sleep"},
  {cz:"srpen",en:"august"},
  {cz:"starat",en:"worrying"},
  {cz:"starosti",en:"to worry"},
  {cz:"stará",en:"old"},
  {cz:"staré",en:"old"},
  {cz:"starý",en:"old"},
  {cz:"starší bratr",en:"older brother"},
  {cz:"starší sestra",en:"older sister"},
  {cz:"stačit",en:"be enough"},
  {cz:"staří",en:"old"},
  {cz:"stejný",en:"same"},
  {cz:"stejně",en:"yet"},
  {cz:"stipendium",en:"scholarship"},
  {cz:"sto",en:"hundred"},
  {cz:"sto tisíc",en:"a hundred thousand"},
  {cz:"století",en:"centuries"},
  {cz:"stoupat",en:"to rise"},
  {cz:"stres",en:"to be stressed"},
  {cz:"stroj",en:"machine"},
  {cz:"strom",en:"tree"},
  {cz:"stromy",en:"trees"},
  {cz:"strávit",en:"to spend"},
  {cz:"strýc",en:"uncle"},
  {cz:"student",en:"student"},
  {cz:"studený",en:"cold"},
  {cz:"studovat tvrdě",en:"to study hard"},
  {cz:"stydlivý",en:"shy"},
  {cz:"styl hudby",en:"Type of music"},
  {cz:"stále",en:"always"},
  {cz:"stárnout",en:"to age"},
  {cz:"stát",en:"to stand"},
  {cz:"stát se",en:"to become"},
  {cz:"stěhovat",en:"to move"},
  {cz:"stěžovat",en:"complain"},
  {cz:"stěžovat si",en:"to complain"},
  {cz:"střecha",en:"roof"},
  {cz:"středa",en:"Wednesday"},
  {cz:"střední",en:"medium"},
  {cz:"stůl",en:"table"},
  {cz:"sukně",en:"skirt"},
  {cz:"supermarket",en:"a supermarket"},
  {cz:"suvenýr",en:"souvenir"},
  {cz:"sušené",en:"dry"},
  {cz:"sval",en:"muscle"},
  {cz:"svalnatý",en:"muscular"},
  {cz:"svatba",en:"wedding"},
  {cz:"svatební cesta",en:"honeymoon"},
  {cz:"svatební dort",en:"wedding cake"},
  {cz:"svačina",en:"a snack"},
  {cz:"svetr",en:"sweater"},
  {cz:"svléknout",en:"to take off"},
  {cz:"svoje",en:"her"},
  {cz:"svoji",en:"their"},
  {cz:"svojí",en:"her"},
  {cz:"svou",en:"your"},
  {cz:"svá",en:"her"},
  {cz:"svátek",en:"holiday"},
  {cz:"své",en:"your"},
  {cz:"svého",en:"your"},
  {cz:"svých",en:"her"},
  {cz:"svědek",en:"witness"},
  {cz:"svět",en:"world"},
  {cz:"světle",en:"light"},
  {cz:"světlý",en:"light"},
  {cz:"svěží",en:"fresh"},
  {cz:"svůj",en:"your"},
  {cz:"sycený nápoj",en:"soft drink"},
  {cz:"syn",en:"son"},
  {cz:"synovec",en:"Nephew"},
  {cz:"sytý",en:"to be full"},
  {cz:"sýr",en:"cheese"},
  {cz:"sůl",en:"salt"},
  {cz:"ta",en:"the"},
  {cz:"tady",en:"here"},
  {cz:"tahle",en:"this"},
  {cz:"tajemství",en:"secret"},
  {cz:"Tajfun",en:"Typhoon"},
  {cz:"tak",en:"that"},
  {cz:"takovém",en:"such"},
  {cz:"takovémhle",en:"like this"},
  {cz:"takovémto",en:"like this"},
  {cz:"takový",en:"like"},
  {cz:"také",en:"also"},
  {cz:"talíř",en:"plate"},
  {cz:"talíře",en:"plates"},
  {cz:"tam",en:"there"},
  {cz:"tamhleta",en:"that"},
  {cz:"tamhleten",en:"that"},
  {cz:"tamhleti",en:"those"},
  {cz:"tamhleto",en:"those"},
  {cz:"tamhletom",en:"that"},
  {cz:"tamta",en:"that one"},
  {cz:"tamten",en:"that"},
  {cz:"tamti",en:"those"},
  {cz:"tamto",en:"that"},
  {cz:"tamtom",en:"that"},
  {cz:"tančit",en:"to dance"},
  {cz:"tato",en:"this"},
  {cz:"taxi",en:"a taxi"},
  {cz:"taška",en:"bag"},
  {cz:"tehdy",en:"then"},
  {cz:"telefon",en:"a phone"},
  {cz:"telefonní číslo",en:"phone number"},
  {cz:"televize",en:"television"},
  {cz:"temný",en:"dark"},
  {cz:"ten",en:"the"},
  {cz:"tenhle",en:"this one"},
  {cz:"tenisky",en:"sneakers"},
  {cz:"tento",en:"this one"},
  {cz:"teplota",en:"temperature"},
  {cz:"teplý",en:"warm"},
  {cz:"teta",en:"aunt"},
  {cz:"teď",en:"now"},
  {cz:"ti",en:"the"},
  {cz:"tihle",en:"these"},
  {cz:"tisíc",en:"thousand"},
  {cz:"tito",en:"these"},
  {cz:"tkanička",en:"shoelace"},
  {cz:"tlustý",en:"fat"},
  {cz:"tmavě",en:"dark"},
  {cz:"to",en:"this"},
  {cz:"toaleta",en:"toilet"},
  {cz:"tofu",en:"tofu"},
  {cz:"tohle",en:"this"},
  {cz:"tom",en:"the"},
  {cz:"tomhle",en:"this"},
  {cz:"tomto",en:"this"},
  {cz:"topení",en:"heater"},
  {cz:"toto",en:"this"},
  {cz:"trajekt",en:"ferry"},
  {cz:"trička",en:"T-shirts"},
  {cz:"tričko",en:"T-shirt"},
  {cz:"trochu",en:"little"},
  {cz:"trouba",en:"oven"},
  {cz:"trvat",en:"insist"},
  {cz:"trávit čas",en:"to spend time"},
  {cz:"tsunami",en:"tsunami"},
  {cz:"tu",en:"that"},
  {cz:"turista",en:"tourist"},
  {cz:"tvoje",en:"yours"},
  {cz:"tvoji",en:"your"},
  {cz:"tvojí",en:"your"},
  {cz:"tvou",en:"your"},
  {cz:"tvrdý",en:"hard"},
  {cz:"tvrdě pracovat",en:"to work hard"},
  {cz:"tvá",en:"your"},
  {cz:"tvář",en:"face"},
  {cz:"tvé",en:"your"},
  {cz:"tvého",en:"your"},
  {cz:"tví",en:"your"},
  {cz:"tvých",en:"your"},
  {cz:"tvůj",en:"yours"},
  {cz:"ty",en:"the"},
  {cz:"táta",en:"dad"},
  {cz:"tátové",en:"dads"},
  {cz:"té",en:"the"},
  {cz:"téma",en:"topic"},
  {cz:"téměř",en:"almost"},
  {cz:"týden",en:"week"},
  {cz:"tým",en:"team"},
  {cz:"tě",en:"you"},
  {cz:"těch",en:"the"},
  {cz:"tělo",en:"body"},
  {cz:"těsný",en:"tight"},
  {cz:"těžký",en:"heavy"},
  {cz:"třetí",en:"third"},
  {cz:"tři",en:"three"},
  {cz:"tři sta",en:"three hundred"},
  {cz:"tři čtvrtě",en:"three quarters"},
  {cz:"tři čtvrtě na ...",en:"quarter to"},
  {cz:"třicet",en:"thirty"},
  {cz:"třináct",en:"thirteen"},
  {cz:"u",en:"at"},
  {cz:"ucho",en:"ear"},
  {cz:"uchovávat",en:"to keep"},
  {cz:"ucházet se",en:"to apply"},
  {cz:"uklízet",en:"to clean"},
  {cz:"ukončit",en:"to quit"},
  {cz:"ukrást",en:"to steal"},
  {cz:"ukázat",en:"to show"},
  {cz:"ulice",en:"street"},
  {cz:"uložit",en:"to deposit"},
  {cz:"umýt",en:"to wash"},
  {cz:"umělec",en:"Artist"},
  {cz:"umět",en:"can"},
  {cz:"unavený",en:"tired"},
  {cz:"uniknout",en:"to escape"},
  {cz:"univerzita",en:"University"},
  {cz:"určitě",en:"definitely"},
  {cz:"usmát se",en:"to smile"},
  {cz:"uvnitř",en:"inside"},
  {cz:"učebna",en:"a classroom"},
  {cz:"učební obor",en:"apprenticeship"},
  {cz:"učit",en:"teaching"},
  {cz:"učit se",en:"to learn"},
  {cz:"učitel",en:"teacher"},
  {cz:"učitelka",en:"teacher"},
  {cz:"uši",en:"ears"},
  {cz:"už",en:"yet"},
  {cz:"užitečný",en:"useful"},
  {cz:"v",en:"at"},
  {cz:"v dobré kondici",en:"in good shape"},
  {cz:"vařit",en:"to cook; to boil"},
  {cz:"vaše",en:"your"},
  {cz:"vašeho",en:"your"},
  {cz:"vašem",en:"your"},
  {cz:"vaši",en:"your"},
  {cz:"vašich",en:"your"},
  {cz:"vaší",en:"your"},
  {cz:"vdaná",en:"married"},
  {cz:"vdova",en:"widow"},
  {cz:"ve",en:"into"},
  {cz:"vejce",en:"egg"},
  {cz:"velcí",en:"big"},
  {cz:"velikost",en:"size"},
  {cz:"velkou",en:"great"},
  {cz:"velká",en:"big"},
  {cz:"velké",en:"large"},
  {cz:"velkého",en:"large"},
  {cz:"velký",en:"big"},
  {cz:"velmi",en:"very much"},
  {cz:"vepřové",en:"pork"},
  {cz:"vesmír",en:"universe"},
  {cz:"vesnice",en:"village"},
  {cz:"večer",en:"evening"},
  {cz:"večeře",en:"dinner"},
  {cz:"vidlička",en:"fork"},
  {cz:"vidí",en:"sees"},
  {cz:"vidět",en:"see"},
  {cz:"vila",en:"villa"},
  {cz:"vinný",en:"guilty"},
  {cz:"vlak",en:"a train"},
  {cz:"vlaková zastávka",en:"a train station"},
  {cz:"vlas",en:"hair"},
  {cz:"vlastní",en:"proper"},
  {cz:"vlasy",en:"hair"},
  {cz:"vlevo",en:"left"},
  {cz:"vlk",en:"wolf"},
  {cz:"vnoučata",en:"Grandchildren"},
  {cz:"voda",en:"water"},
  {cz:"vodní meloun",en:"a watermelon"},
  {cz:"vodopád",en:"water fall"},
  {cz:"voják",en:"Soldier"},
  {cz:"volat",en:"to call"},
  {cz:"volný",en:"loose"},
  {cz:"vonný",en:"fragrant"},
  {cz:"vražda",en:"murder"},
  {cz:"vrátit se",en:"to come back"},
  {cz:"vstoupit",en:"to come in; to enter"},
  {cz:"vstupné",en:"entrance fee"},
  {cz:"vstupní hala",en:"the lobby"},
  {cz:"vstát",en:"to get up"},
  {cz:"vteřina",en:"a second"},
  {cz:"vy",en:"you"},
  {cz:"vybrat",en:"to withdraw; to choose"},
  {cz:"vyhnat",en:"to uproot"},
  {cz:"vyhrát",en:"to win"},
  {cz:"vyjádřit",en:"to express"},
  {cz:"vykrást",en:"to rob"},
  {cz:"vyměnit",en:"to exchange; to replace"},
  {cz:"vypadat",en:"look"},
  {cz:"vypadat jako",en:"to look like"},
  {cz:"vyplnit",en:"to fill"},
  {cz:"vypnout",en:"to shut down"},
  {cz:"vypnout mobilní telefon",en:"to turn off a cellphone"},
  {cz:"vypít",en:"drink"},
  {cz:"vyrábět",en:"produce"},
  {cz:"vyskytovat",en:"to occur"},
  {cz:"vysoké podpatky",en:"high heels"},
  {cz:"vysoký",en:"tall"},
  {cz:"vystoupit",en:"to get off"},
  {cz:"vystoupit z autobusu",en:"to get off the bus"},
  {cz:"vysvětlit",en:"to explain"},
  {cz:"vyzout",en:"to take off"},
  {cz:"vyzvednout",en:"to pick up"},
  {cz:"vyřešit",en:"to fix; to solve"},
  {cz:"vzhled",en:"appearance"},
  {cz:"vzít",en:"hold"},
  {cz:"válka",en:"war"},
  {cz:"Vánoce",en:"Christmas"},
  {cz:"vás",en:"you"},
  {cz:"vázanka",en:"necktie"},
  {cz:"váš",en:"your"},
  {cz:"vážit",en:"weigh"},
  {cz:"vést",en:"to lead"},
  {cz:"více",en:"more"},
  {cz:"víkend",en:"weekend"},
  {cz:"víno",en:"wine"},
  {cz:"vízum",en:"Visa"},
  {cz:"východ",en:"exit"},
  {cz:"výlet",en:"trip"},
  {cz:"výročí",en:"anniversary"},
  {cz:"výsledek",en:"result"},
  {cz:"včela",en:"bee"},
  {cz:"včera",en:"yesterday"},
  {cz:"věc",en:"thing"},
  {cz:"věci",en:"objects"},
  {cz:"vědět",en:"know"},
  {cz:"věta",en:"sentence"},
  {cz:"větrný",en:"windy"},
  {cz:"všechno",en:"all"},
  {cz:"všední den",en:"weekday"},
  {cz:"všude",en:"everywhere"},
  {cz:"vůbec",en:"at all"},
  {cz:"vždy",en:"always"},
  {cz:"webová stránka",en:"Website"},
  {cz:"z",en:"out"},
  {cz:"za",en:"behind"},
  {cz:"zabrat",en:"to take"},
  {cz:"zabít",en:"to kill"},
  {cz:"zahrada",en:"backyard"},
  {cz:"zajímat",en:"to interest"},
  {cz:"zajímavý",en:"interesting"},
  {cz:"zamíchat",en:"to stir fry; to mix"},
  {cz:"zaměstnanec",en:"employee"},
  {cz:"zaměstnavatel",en:"employer"},
  {cz:"zaneprázdněný",en:"busy"},
  {cz:"zaplavit",en:"flood"},
  {cz:"zapnout",en:"to turn on"},
  {cz:"zapnout mobilní telefon",en:"to turn on a cellphone"},
  {cz:"zapomenout",en:"haven't"},
  {cz:"zaregistrovat se",en:"to register"},
  {cz:"zase",en:"again"},
  {cz:"zastavit",en:"to stop"},
  {cz:"zatmění Měsíce",en:"lunar eclipse"},
  {cz:"zatmění Slunce",en:"solar eclipse"},
  {cz:"zatímco",en:"as"},
  {cz:"zavazadlo",en:"luggage"},
  {cz:"zavřený",en:"closed"},
  {cz:"zavřít",en:"to close"},
  {cz:"začínat",en:"starting"},
  {cz:"začít",en:"let's"},
  {cz:"zařízení",en:"facility"},
  {cz:"zbývat",en:"to remain"},
  {cz:"zde",en:"here"},
  {cz:"zdravotní sestřička",en:"nurse"},
  {cz:"zdraví",en:"health"},
  {cz:"zdravý",en:"healthy"},
  {cz:"zelenina",en:"vegetables"},
  {cz:"zelená",en:"green"},
  {cz:"zelený",en:"green"},
  {cz:"zelený čaj",en:"green tea"},
  {cz:"země",en:"Country; earth"},
  {cz:"zemětřesení",en:"earthquake"},
  {cz:"zemřít",en:"to die"},
  {cz:"zeptat se",en:"to ask"},
  {cz:"zima",en:"cold"},
  {cz:"zisk",en:"profit"},
  {cz:"zjišťovat",en:"to find"},
  {cz:"zkontrolovat",en:"to check"},
  {cz:"zkouška",en:"exam"},
  {cz:"zkusit",en:"to try"},
  {cz:"zkušenost",en:"experience"},
  {cz:"zlato",en:"gold"},
  {cz:"zlepšit",en:"to improve"},
  {cz:"zlomit",en:"to break"},
  {cz:"zločin",en:"crime"},
  {cz:"zmrzlina",en:"ice cream"},
  {cz:"znamenat",en:"to mean"},
  {cz:"značka",en:"sign"},
  {cz:"zničit",en:"to destroy; to ruin"},
  {cz:"znuděný",en:"bored"},
  {cz:"známý",en:"well-known"},
  {cz:"znát",en:"know"},
  {cz:"zoologická zahrada",en:"a zoo"},
  {cz:"zotavit",en:"to recover"},
  {cz:"zpráva",en:"message"},
  {cz:"zprávy",en:"news"},
  {cz:"zpívat",en:"sing"},
  {cz:"zpěvák",en:"singer"},
  {cz:"způsobit",en:"to cause"},
  {cz:"zranit",en:"to get hurt"},
  {cz:"zrušit",en:"to cancel"},
  {cz:"ztracený",en:"missing"},
  {cz:"zub",en:"tooth"},
  {cz:"zubař",en:"dentist"},
  {cz:"zvláštní",en:"peculiar"},
  {cz:"zvířata",en:"animals"},
  {cz:"zvíře",en:"animal"},
  {cz:"zábava",en:"fun"},
  {cz:"záchod",en:"restroom"},
  {cz:"záchranná služba",en:"ambulance"},
  {cz:"záclony",en:"curtains"},
  {cz:"záměr",en:"purpose"},
  {cz:"západ",en:"west"},
  {cz:"září",en:"September"},
  {cz:"získat",en:"to get"},
  {cz:"zítra",en:"tomorrow"},
  {cz:"zřídka",en:"rarely"},
  {cz:"zůstat",en:"to stay"},
  {cz:"údaje",en:"data"},
  {cz:"únor",en:"February"},
  {cz:"úplně",en:"completely"},
  {cz:"úplněk",en:"full moon"},
  {cz:"úsměv",en:"smile"},
  {cz:"úspěch",en:"success"},
  {cz:"úspěšný",en:"successful"},
  {cz:"ústa",en:"mouth"},
  {cz:"úterý",en:"Tuesday"},
  {cz:"účet",en:"a bill"},
  {cz:"účtenka",en:"a receipt"},
  {cz:"úředník",en:"Office worker"},
  {cz:"čaj",en:"tea"},
  {cz:"čas",en:"time"},
  {cz:"časopis",en:"magazine"},
  {cz:"často",en:"often"},
  {cz:"čech",en:"Czech"},
  {cz:"čeho",en:"what"},
  {cz:"čekat",en:"wait"},
  {cz:"čepice",en:"hat"},
  {cz:"černobílá",en:"black and white"},
  {cz:"černá",en:"black"},
  {cz:"černý",en:"black"},
  {cz:"čerstvé",en:"fresh"},
  {cz:"červen",en:"June"},
  {cz:"červenec",en:"july"},
  {cz:"červená",en:"red"},
  {cz:"červené víno",en:"red wine"},
  {cz:"červený",en:"red"},
  {cz:"česky",en:"Czech"},
  {cz:"česnek",en:"garlic"},
  {cz:"češka",en:"Czech woman"},
  {cz:"čistit si zuby",en:"to brush one&#x27;s teeth"},
  {cz:"čistý",en:"purifies"},
  {cz:"člověk",en:"man"},
  {cz:"člověka",en:"man"},
  {cz:"čtrnáct",en:"fourteen"},
  {cz:"čtrnáctý",en:"fourteenth"},
  {cz:"čtvrt",en:"quarter"},
  {cz:"čtvrt na ...",en:"quarter past"},
  {cz:"čtvrtek",en:"Thursday"},
  {cz:"čtvrtý",en:"fourth"},
  {cz:"čtyři",en:"four"},
  {cz:"čtyři sta",en:"four hundred"},
  {cz:"čtyřicet",en:"forty"},
  {cz:"čí",en:"whose"},
  {cz:"Čína",en:"China"},
  {cz:"čínština",en:"Chinese"},
  {cz:"číslo",en:"number"},
  {cz:"číslo domu",en:"house number"},
  {cz:"číst",en:"read"},
  {cz:"řeka",en:"river"},
  {cz:"řezat",en:"to cut"},
  {cz:"řešení",en:"solution"},
  {cz:"řešit",en:"to deal"},
  {cz:"řidič",en:"a driver"},
  {cz:"říct",en:"to tell"},
  {cz:"říjen",en:"October"},
  {cz:"říkat",en:"saying"},
  {cz:"šance",en:"chance"},
  {cz:"šaty",en:"dresses"},
  {cz:"šedesát",en:"sixty"},
  {cz:"šedá",en:"gray"},
  {cz:"šel",en:"he went"},
  {cz:"šest",en:"six"},
  {cz:"šest set",en:"six hundred"},
  {cz:"šestnáct",en:"sixteen"},
  {cz:"šestnáctý",en:"sixteenth"},
  {cz:"šestý",en:"sixth"},
  {cz:"široký",en:"wide"},
  {cz:"škola",en:"school"},
  {cz:"školení",en:"training"},
  {cz:"školy",en:"school"},
  {cz:"španělština",en:"Spanish"},
  {cz:"špatné",en:"wrong"},
  {cz:"špatný",en:"bad"},
  {cz:"špatně",en:"bad"},
  {cz:"šperk",en:"jewel"},
  {cz:"špinavý",en:"dirty"},
  {cz:"štíhlý",en:"thin"},
  {cz:"štěstí",en:"happiness; luck"},
  {cz:"šálek",en:"cup"},
  {cz:"šátek",en:"scarf"},
  {cz:"šéf",en:"boss"},
  {cz:"šílený",en:"crazy"},
  {cz:"šťastný",en:"happy"},
  {cz:"žadatel",en:"applicant"},
  {cz:"žaludek",en:"stomach"},
  {cz:"žampion",en:"a mushroom"},
  {cz:"že",en:"right"},
  {cz:"žena",en:"woman"},
  {cz:"ženatý",en:"married"},
  {cz:"ženu",en:"wife"},
  {cz:"ženy",en:"wife's"},
  {cz:"židle",en:"chair"},
  {cz:"život",en:"life"},
  {cz:"živý",en:"alive"},
  {cz:"žlutá",en:"yellow"},
  {cz:"žofie",en:"(leave as is)"},
  {cz:"žofii",en:"Žofie"},
  {cz:"žrádlo",en:"food"},
  {cz:"žrát",en:"eat"},
  {cz:"žít",en:"to live"},
  {cz:"žízeň",en:"thirst"},
  {cz:"žíznivý",en:"thirsty"},
];
